name: Expo Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'android'
        type: choice
        options:
          - android
          - ios

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Expo CLI
        run: npm install -g @expo/cli

      - name: Install dependencies
        run: npm install

      - name: Build with Expo
        run: |
          echo "Building for ${{ github.event.inputs.platform }}"
          npx expo build:${{ github.event.inputs.platform }} --non-interactive